//=============================================================================
// tb_aes128_iterative.v -- self-checking testbench for the iterative core
//
// Checks, in order:
//   1. FIPS-197 / SP 800-38A known-answer vectors, read from a file that is
//      generated by an independent Python model (model/aes_golden.py).
//   2. Every remaining vector in that file (1000+ randomised key/plaintext
//      pairs) run back-to-back.
//   3. Protocol assertions: exact 11-cycle latency, done is a single pulse,
//      busy behaves, ciphertext holds until the next block is accepted.
//   4. Reset behaviour mid-transaction.
//
// Exits non-zero via $fatal if anything fails, so it can gate CI.
//
//   iverilog -g2012 -o sim.vvp tb/tb_aes128_iterative.v rtl/*.v && vvp sim.vvp
//=============================================================================
`timescale 1ns / 1ps
`default_nettype none

module tb_aes128_iterative;

    // 384.6 MHz target -> 2.6 ns period
    localparam real CLK_PERIOD = 2.6;

    reg          clk = 1'b0;
    reg          rst_n = 1'b0;
    reg          start = 1'b0;
    reg  [127:0] key = 128'd0;
    reg  [127:0] plaintext = 128'd0;
    wire         busy;
    wire         done;
    wire [127:0] ciphertext;

    integer errors = 0;
    integer checks = 0;

    aes128_iterative dut (
        .clk        (clk),
        .rst_n      (rst_n),
        .start      (start),
        .key        (key),
        .plaintext  (plaintext),
        .busy       (busy),
        .done       (done),
        .ciphertext (ciphertext)
    );

    always #(CLK_PERIOD / 2.0) clk = ~clk;

    //-------------------------------------------------------------------------
    // Drive one block and check the result, measuring latency in cycles
    //-------------------------------------------------------------------------
    task run_block (
        input [127:0] k,
        input [127:0] pt,
        input [127:0] expected,
        input [8*32-1:0] label
    );
        integer cycles;
        begin
            @(negedge clk);
            key       = k;
            plaintext = pt;
            start     = 1'b1;
            @(negedge clk);
            start = 1'b0;

            if (busy !== 1'b1) begin
                $display("ERROR [%0s]: busy did not assert after start", label);
                errors = errors + 1;
            end

            cycles = 1;
            while (done !== 1'b1) begin
                if (cycles > 40) begin
                    $display("ERROR [%0s]: done never asserted (hang)", label);
                    errors = errors + 1;
                    disable run_block;
                end
                @(negedge clk);
                cycles = cycles + 1;
            end

            checks = checks + 1;

            if (cycles !== 11) begin
                $display("ERROR [%0s]: latency %0d cycles, expected 11",
                         label, cycles);
                errors = errors + 1;
            end

            if (ciphertext !== expected) begin
                $display("ERROR [%0s]:", label);
                $display("        key = %032h", k);
                $display("         pt = %032h", pt);
                $display("        got = %032h", ciphertext);
                $display("        exp = %032h", expected);
                errors = errors + 1;
            end

            // done must be a single-cycle pulse, ciphertext must hold
            @(negedge clk);
            if (done !== 1'b0) begin
                $display("ERROR [%0s]: done asserted for more than one cycle",
                         label);
                errors = errors + 1;
            end
            if (ciphertext !== expected) begin
                $display("ERROR [%0s]: ciphertext not held after done", label);
                errors = errors + 1;
            end
        end
    endtask

    //-------------------------------------------------------------------------
    // Vector file playback
    //-------------------------------------------------------------------------
    integer fd, code, vec_num;
    reg [127:0] v_key, v_pt, v_ct;
    reg [8*256-1:0] line_rest;

    //-------------------------------------------------------------------------
    // Reset-during-operation check
    //-------------------------------------------------------------------------
    task check_reset_midflight;
        begin
            @(negedge clk);
            key       = 128'h000102030405060708090a0b0c0d0e0f;
            plaintext = 128'h00112233445566778899aabbccddeeff;
            start     = 1'b1;
            @(negedge clk);
            start = 1'b0;
            repeat (4) @(negedge clk);      // abort mid-round
            rst_n = 1'b0;
            @(negedge clk);
            if (busy !== 1'b0 || done !== 1'b0) begin
                $display("ERROR: reset did not clear busy/done");
                errors = errors + 1;
            end
            rst_n = 1'b1;
            @(negedge clk);
            // core must accept a fresh block immediately after reset
            run_block(128'h000102030405060708090a0b0c0d0e0f,
                      128'h00112233445566778899aabbccddeeff,
                      128'h69c4e0d86a7b0430d8cdb78070b4c55a,
                      "post-reset restart");
        end
    endtask

    //-------------------------------------------------------------------------
    // Back-to-back throughput check: issue the next start on the done cycle
    //-------------------------------------------------------------------------
    task check_back_to_back;
        integer i, gap;
        reg [127:0] exp0, exp1;
        begin
            exp0 = 128'h3925841d02dc09fbdc118597196a0b32;
            exp1 = 128'h69c4e0d86a7b0430d8cdb78070b4c55a;

            @(negedge clk);
            key       = 128'h2b7e151628aed2a6abf7158809cf4f3c;
            plaintext = 128'h3243f6a8885a308d313198a2e0370734;
            start     = 1'b1;
            @(negedge clk);
            start = 1'b0;

            gap = 1;
            while (done !== 1'b1) begin
                @(negedge clk);
                gap = gap + 1;
            end
            if (ciphertext !== exp0) begin
                $display("ERROR [b2b]: first block got %032h exp %032h",
                         ciphertext, exp0);
                errors = errors + 1;
            end

            // start again on the very cycle done is high
            key       = 128'h000102030405060708090a0b0c0d0e0f;
            plaintext = 128'h00112233445566778899aabbccddeeff;
            start     = 1'b1;
            @(negedge clk);
            start = 1'b0;
            if (busy !== 1'b1) begin
                $display("ERROR [b2b]: core did not accept start on done cycle");
                errors = errors + 1;
            end

            gap = 1;
            while (done !== 1'b1) begin
                @(negedge clk);
                gap = gap + 1;
            end
            if (gap !== 11) begin
                $display("ERROR [b2b]: second block latency %0d, expected 11",
                         gap);
                errors = errors + 1;
            end
            if (ciphertext !== exp1) begin
                $display("ERROR [b2b]: second block got %032h exp %032h",
                         ciphertext, exp1);
                errors = errors + 1;
            end
            checks = checks + 2;
            $display("  [PASS] back-to-back issue, 11-cycle initiation interval");
        end
    endtask

    //-------------------------------------------------------------------------
    // Start must be ignored while busy
    //-------------------------------------------------------------------------
    task check_start_ignored_while_busy;
        integer cycles;
        begin
            @(negedge clk);
            key       = 128'h2b7e151628aed2a6abf7158809cf4f3c;
            plaintext = 128'h6bc1bee22e409f96e93d7e117393172a;
            start     = 1'b1;
            @(negedge clk);
            // hold start high through the whole operation and corrupt the
            // inputs -- an accepted re-start would produce the wrong answer
            key       = 128'hdeadbeefdeadbeefdeadbeefdeadbeef;
            plaintext = 128'hcafebabecafebabecafebabecafebabe;
            cycles = 1;
            while (done !== 1'b1) begin
                @(negedge clk);
                cycles = cycles + 1;
                if (cycles > 40) begin
                    $display("ERROR [busy]: hang with start held high");
                    errors = errors + 1;
                    disable check_start_ignored_while_busy;
                end
            end
            start = 1'b0;
            if (cycles !== 11) begin
                $display("ERROR [busy]: latency %0d with start held, expected 11",
                         cycles);
                errors = errors + 1;
            end
            if (ciphertext !== 128'h3ad77bb40d7a3660a89ecaf32466ef97) begin
                $display("ERROR [busy]: start was not ignored while busy");
                $display("        got = %032h", ciphertext);
                errors = errors + 1;
            end else begin
                $display("  [PASS] start ignored while busy");
            end
            checks = checks + 1;
            @(negedge clk);
        end
    endtask

    //-------------------------------------------------------------------------
    // Main sequence
    //-------------------------------------------------------------------------
    initial begin
        if ($test$plusargs("dumpvcd")) begin
            $dumpfile("tb_aes128_iterative.vcd");
            $dumpvars(0, tb_aes128_iterative);
        end

        $display("");
        $display("=====================================================");
        $display(" AES-128 iterative core -- self-checking testbench");
        $display(" clock period %0.2f ns (%0.1f MHz)",
                 CLK_PERIOD, 1000.0 / CLK_PERIOD);
        $display("=====================================================");

        repeat (4) @(negedge clk);
        rst_n = 1'b1;
        repeat (2) @(negedge clk);

        $display("");
        $display("-- Directed NIST known-answer tests ------------------");
        run_block(128'h2b7e151628aed2a6abf7158809cf4f3c,
                  128'h3243f6a8885a308d313198a2e0370734,
                  128'h3925841d02dc09fbdc118597196a0b32,
                  "FIPS-197 App. B");
        run_block(128'h000102030405060708090a0b0c0d0e0f,
                  128'h00112233445566778899aabbccddeeff,
                  128'h69c4e0d86a7b0430d8cdb78070b4c55a,
                  "FIPS-197 App. C.1");
        run_block(128'h00000000000000000000000000000000,
                  128'h00000000000000000000000000000000,
                  128'h66e94bd4ef8a2c3b884cfa59ca342b2e,
                  "AESAVS all-zero");
        if (errors == 0)
            $display("  [PASS] %0d directed vectors, 11-cycle latency each",
                     checks);

        $display("");
        $display("-- Protocol checks -----------------------------------");
        check_start_ignored_while_busy;
        check_back_to_back;
        check_reset_midflight;

        $display("");
        $display("-- Vector file regression ----------------------------");
        fd = $fopen("tb/vectors/aes128_vectors.txt", "r");
        if (fd == 0) fd = $fopen("vectors/aes128_vectors.txt", "r");
        if (fd == 0) begin
            $display("ERROR: cannot open tb/vectors/aes128_vectors.txt");
            $display("       run: python model/aes_golden.py --gen-vectors ...");
            errors = errors + 1;
        end else begin
            vec_num = 0;
            while (!$feof(fd)) begin
                code = $fscanf(fd, "%h %h %h", v_key, v_pt, v_ct);
                if (code == 3) begin
                    vec_num = vec_num + 1;
                    run_block(v_key, v_pt, v_ct, "vecfile");
                    if (errors > 10) begin
                        $display("ERROR: too many failures, stopping early");
                        vec_num = -1;
                        code = 0;
                    end
                end
                // skip to end of line (comments / header)
                if (code != 3) code = $fgets(line_rest, fd);
                if (vec_num == -1) code = 0;
            end
            $fclose(fd);
            if (vec_num > 0)
                $display("  [PASS] %0d file vectors matched the golden model",
                         vec_num);
        end

        $display("");
        $display("=====================================================");
        $display(" blocks encrypted : %0d", checks);
        $display(" errors           : %0d", errors);
        if (errors == 0) begin
            $display(" RESULT           : *** ALL TESTS PASSED ***");
            $display("=====================================================");
            $display("");
            $finish;
        end else begin
            $display(" RESULT           : *** FAILED ***");
            $display("=====================================================");
            $display("");
            $fatal(1);
        end
    end

    // global watchdog
    initial begin
        #20_000_000;
        $display("ERROR: global timeout");
        $fatal(1);
    end

endmodule

`default_nettype wire
